export const defaultStyle = '4px solid rgb(0, 50, 255)'
export const changingStyle = '4px solid rgb(210, 82, 225)'
export const modifiedStyle = '4px solid rgb(127, 224, 81)'

export const circle = 'div[class*="circle_circle"]'
export const circleContent = 'div[class*="circle_content"]'

export const input = '[data-id="input"]'
export const calculateBtn = '[data-id="calculate"]'
export const addHeadBtn = '[data-id="add-head"]'
export const addTailBtn = '[data-id="add-tail"]'
export const addIndexBtn = '[data-id="add-index"]'
export const deleteHeadBtn = '[data-id="delete-head"]'
export const deleteTailBtn = '[data-id="delete-tail"]'
export const deleteIndexBtn = '[data-id="delete-index"]'
export const inputIndex = '[data-id="input-index"]'
export const addBtn = '[data-id="add"]'
export const deleteBtn = '[data-id="delete"]'
export const clearBtn = '[data-id="clear"]'
export const reverseBtn = '[data-id="reverse"]'
