import { defaultStyle, circle } from '../constants'
import { SHORT_DELAY_IN_MS } from '../../../src/constants/delays'

describe('Фибоначчи', () => {
	it('Eсли в инпуте пусто, то кнопка добавления недоступна', () => {
		cy.visit('http://localhost:3000/fibonacci')
		cy.get('input').clear()
		cy.get('[data-id="calculate"]').should('be.disabled')
	})

	it('Числа генерируются корректно', () => {
		cy.visit('http://localhost:3000/fibonacci')
		cy.get('input').type('5').should('have.value', '5')
		cy.get('[data-id="calculate"]').should('not.be.disabled').click()

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')

		cy.wait(SHORT_DELAY_IN_MS)

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(1)
			.should('have.css', 'border', defaultStyle)
			.contains('1')

		cy.wait(SHORT_DELAY_IN_MS)

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(1)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(2)
			.should('have.css', 'border', defaultStyle)
			.contains('2')

		cy.wait(SHORT_DELAY_IN_MS)

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(1)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(2)
			.should('have.css', 'border', defaultStyle)
			.contains('2')
		cy.get(circle)
			.eq(3)
			.should('have.css', 'border', defaultStyle)
			.contains('3')

		cy.wait(SHORT_DELAY_IN_MS)

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(1)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(2)
			.should('have.css', 'border', defaultStyle)
			.contains('2')
		cy.get(circle)
			.eq(3)
			.should('have.css', 'border', defaultStyle)
			.contains('3')
		cy.get(circle)
			.eq(4)
			.should('have.css', 'border', defaultStyle)
			.contains('5')

		cy.wait(SHORT_DELAY_IN_MS)

		cy.get(circle)
			.eq(0)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(1)
			.should('have.css', 'border', defaultStyle)
			.contains('1')
		cy.get(circle)
			.eq(2)
			.should('have.css', 'border', defaultStyle)
			.contains('2')
		cy.get(circle)
			.eq(3)
			.should('have.css', 'border', defaultStyle)
			.contains('3')
		cy.get(circle)
			.eq(4)
			.should('have.css', 'border', defaultStyle)
			.contains('5')
		cy.get(circle)
			.eq(5)
			.should('have.css', 'border', defaultStyle)
			.contains('8')
	})
})
